export const endpointToMethod = new Proxy(
  {
    "car/assets": "getCarAssets",
    "car/get": "getCars",
    "carclass/get": "getCarClasses",
    "constants/categories": "getCategories",
    "constants/divisions": "getDivisions",
    "constants/event_types": "getEventTypes",
    "hosted/combined_sessions": "getHostedCombinedSessions",
    "hosted/sessions": "getHostedSessions",
    "league/cust_league_sessions": "getCustLeagueSessions",
    "league/directory": "getLeagueDirectory",
    "league/get": "getLeagueData",
    "league/get_points_systems": "getLeaguePointSystem",
    "league/membership": "getLeagueMembership",
    "league/seasons": "getLeagueSeasons",
    "league/season_standings": "getLeagueSeasonStandings",
    "league/season_sessions": "getLeagueSeasonSessions",
    "lookup/club_history": "getClubHistory",
    "lookup/countries": "getCountries",
    "lookup/drivers": "getDrivers",
    "lookup/licenses": "getLicenses",
    "member/awards": "getMemberAwards",
    "member/chart_data": "getMemberChartData",
    "member/get": "getMemberData",
    "member/info": "getMemberInfo",
    "member/participation_credits": "getMemberParticipationCredits",
    "member/profile": "getMemberProfile",
    "results/get": "getResults",
    "results/event_log": "getResultsEventLog",
    "results/lap_chart_data": "getResultsLapChartData",
    "results/lap_data": "getResultsLapData",
    "results/search_hosted": "searchHosted",
    "results/search_series": "searchSeries",
    "results/season_results": "getSeasonResults",
    "results/seasson_results": "getSeasonResults",
    "season/list": "getSeasonList",
    "season/race_guide": "getSeasonRaceGuide",
    "series/assets": "getSeriesAssets",
    "series/get": "getSeriesData",
    "series/past_seasons": "getSeriesPastSeasons",
    "series/seasons": "getSeriesSeasons",
    "series/stats_series": "getSeriesStats",
    "stats/member_bests": "getMemberBests",
    "stats/member_career": "getMemberCareer",
    "stats/member_division": "getMemberDivision",
    "stats/member_recap": "getMemberRecap",
    "stats/member_recent_races": "getMemberRecentRaces",
    "stats/member_summary": "getMemberSummary",
    "stats/member_yearly": "getMemberYearlyStats",
    "stats/season_driver_standings": "getDriverSeasonStandings",
    "stats/season_supersession_standings": "getSupersessionSeasonStandings",
    "stats/season_team_standings": "getTeamSeasonStandings",
    "stats/season_tt_standings": "getTimeTrialSeasonStandings",
    "stats/season_tt_results": "getTimeTrialSeasonResults",
    "stats/season_qualify_results": "getQualifySeasonResults",
    "stats/world_records": "getWorldRecords",
    "team/get": "getTeamData",
    "time_attack/member_season_results": "getTimeAttackSeasonResults",
    "track/assets": "getTrackAssets",
    "track/get": "getTrackData",
  },
  {
    get: (target: Record<string, string>, endpoint: string) =>
      target[endpoint] ?? undefined,
  },
);
